---
application:
  name: "etestzone"
  project: "etestzone"
  organization: "QoveryCommunity"
  publicly_accessible: true
  port: 3000

routers:
- name: "main-etestzone"
  custom_domains:
  - branch: main
    domain: etestzone.in
  routes:
  - application_name: "etestzone"
    paths:
    - "/*"
